### ISSUE TITLE
Keyboard configuration

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#12]
It would be nice if the user will be able to configure which two keyboard keys to use during the experiment by changing the Keyboard_keys_used_to_respond: as defined in the Configuration.txt file. I hope you can make this change, thanks.
![image](https://user-images.githubusercontent.com/16345231/96400285-55fbc380-119e-11eb-9cad-2183f5d02b5b.png)

**Comment by skalogryz** [comment]
The support for the option has been added. The keys to be used should be provided separated by space:
`Keyboard_keys_used_to_respond: z x`
(obviously the use of space itself is not allowed).
The only keys that can be used are numeric 1 to 9 and 0 (Not Keypad!) and only letter keys (from A to Z), except for "P" (which corresponds to the PAUSE). Symbolic keys (i.e. < {  etc) are NOT supported.

The first key specified corresponds to mouse LEFT click.
The second key specified corresponds to mouse RIGHT click

**Comment by skalogryz** [comment]
if the option is NOT specified, 
OR only ONE valid key char is provided 
OR both key chars are the same 
the system would fallback to the default 'A' (left click) and 'F' (right click selections)

The system retains the keypad 1 (left click) and 4 (right click) keyboard shortcuts. Those cannot be disabled or reconfigured at the current version of the code.

'P' remains as a pause button

**Comment by gfuggetta-lab** [comment]
This issue has been successfully implemented. Thanks
