### ISSUE TITLE
output file availability

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#15]
As you wrote in a previous email, **students might struggle to find the Output *.txt file of their behavioural results** that they should send to me via email or upload on a link on-line to allow me to receive and analyse their empirical data. So, one possible solution would be to have on the main Experiment window a tick box **(default is OFF: no tick):** **“Save a copy of output data on Desktop? [_]”**. If the box is ticked, then the program saves a copy of the participant Output.txt file on Desktop of both Windows OS and Mac OS.

**Comment by skalogryz** [comment]
in order to address the issue of finding the result file, the "complete" form now includes "Open Results Folder" button.
Pressing the button opens the system file manager (i.e. "Explorer" on Windows or "Finder" on macOS) at the folder where the Output file was designated to

The caption of the form also contains the name of the file. However, the user should be able to determine the latest changed file based on the Modification date of the file

![image](https://user-images.githubusercontent.com/16345231/97818741-38385f00-1c72-11eb-9d40-6a1da61aa28c.png)

**Comment by gfuggetta-lab** [comment]
This issue has been successfully solved. Thanks.
