### ISSUE TITLE
Shape Sizing

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#18]
Shape_size_deg: 1.6 
Comment: this parameter currently controls: 9:square, 10:circle and 11:star.

Shape_scale_factor: 1.4 
Comment: this parameter currently controls: 1:diamond, 2:hexagon, 3:triangle, 4:box, 5:ring, 6:plus_+, 7:horiz_bar, 8:vert_bar. In principle, it should be nice if all these
shapes will be controlled by a unique parameter Shape_size_deg. However, I
understand that this can be challenging to code. So, if you prefer, I can just adapt the
Shape scale factor for these shapes with trials and errors to match the physical size
on screen of the three shapes controlled by the Shape_size_deg.

**Comment by gfuggetta-lab** [comment]
All shapes are currently controlled by the parameter shaps size deg. However, not all the shapes have a similar size on screen. So there is no consistency in the degrees of visual angle covered by all shapes. This would be a future implementation of the software.

**Comment by gfuggetta-lab** [comment]
In future experiments, all possible shapes can be produced by simply creating *.bmp images that can be loaded and shown. So this implementation has a low priority.
