### ISSUE TITLE
update Photodiode display

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#21]
Match the parameters of photodiode patches for Windows users having the Trigger station
hardware device with those parameters of photodiode patches specified in the Configuration.txt file.

The features (i.e. size, position) of **S1, S2, S3, S4 and feedback patches** shown at their onset on screen if Windows
OS users have also the software of Trigger station device installed on their machines, **should match** the parameters
of **S3_photodiode_patch** as defined in the configuration.txt file.

The features (i.e. size, position) of **TMS_S3 patch** shown on screen taking into account the time in milliseconds
specified in the “TMS_s3_SOA” parameter as part of the InputData_x.txt file, if Windows OS users have also the
software of Trigger station device installed on their machines, **should match** the parameters of
**TMS_S3_photodiode_patch** as defined in the configuration.txt file.

Comment: with this implementation we ensure consistency in the program’s behaviour between Windows OS users
having also the “Trigger station” hardware in their labs like myself, and both Windows OS and Mac OS users who do
not have the Trigger station hardware.

**Comment by gfuggetta-lab** [comment]
This issue has been solved. Thanks.
