### ISSUE TITLE
Show_S2_placeholder_when_centre

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#22]
Show_S2_placeholder_when_centre: 0 [1 yes 0 no]
This feature is similar to the “Show_S3_placeholder_when_centre: 0 [1 yes 0 no]” and
“Show_S4_placeholder_when_centre: 0 [1 yes 0 no]” features that have been implemented already.

**Comment by gfuggetta-lab** [comment]
This feature of the software is not required anymore, Thanks
