### ISSUE TITLE
Cross-platform application

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#7]
An application created using Lazarus on one platform can generally compile and execute on any platform for which a Free Pascal compiler exists. For desktop applications a single source can target Mac, Linux, and Windows, with little or no modification. It would be great if the software could be compiled for Windows, Linux and macOS.

**Comment by gfuggetta-lab** [comment]
The application has been successfully compiled for both Windows and MacOS.

Many thanks to skalogryz for his fundamental contribution in additional development, optimisation of the software and to have compiled it for MacOS.
