### ISSUE TITLE
Application Certificate check

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#8]
The first time ever that the application is run on a Windows 10 PC, the OS is checking with the user if the application can be trusted. Is there a possibility to avoid this warning message to appear on screen (i.e. allow Windows OS to recognise the application that the can be trusted)? As Publisher instead of Unknown publisher, could we put **Lazarus**, please? Perhaps this will solve the problem.
![image](https://user-images.githubusercontent.com/16345231/96400106-f3a2c300-119d-11eb-98a8-94ae048a2376.png)

**Comment by gfuggetta-lab** [comment]
This issue cannot be resolved unsell there is a payment in place to register the program. So it is not an issue related with coding the software.
