### ISSUE TITLE
Audio white noise

### ISSUE THREAD

**Issue by skalogryz** [gfuggetta-lab/WorkingMemoryAnalyser#9]
As soon as the user clicks on “Begin”, just before the “Training block of trials” begins, it seems that the software in resetting the audio card and makes an annoying “burp” noise from the speakers. Would it be possible to remove that noise, please

**Comment by gfuggetta-lab** [comment]
This is a minor issue that doesn't need to be solved for the current version ofvtge software. Tganks.
